# Generated by Django 4.2.7 on 2023-12-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_carinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
