# Generated by Django 4.2.7 on 2023-12-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_car_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='bio',
            new_name='description',
        ),
    ]
